---
- name: Register RHEL system with subscription-manager using Simple Content Access
  hosts: all
  become: yes
  tasks:

# Do not assume the inventory_hostname is resolvable and delay 10 seconds at start
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      ansible.builtin.wait_for:
        port: 22
        host: arrowvirt-web-dev-04
        search_regex: OpenSSH
        delay: 30
      connection: local
