---
- name: Register RHEL system with subscription-manager using Simple Content Access
  hosts: all
  become: yes
  tasks:

# Do not assume the inventory_hostname is resolvable and delay 10 seconds at start
    - name: Sleep for 300 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 30
      delegate_to: localhost
