---
- name: Register RHEL system with subscription-manager using Simple Content Access
  hosts: all
  become: yes
  tasks:
    - name: Ensure subscription-manager is installed
      ansible.builtin.dnf:
        name: subscription-manager
        state: present

    - name: Register the system with Red Hat subscription-manager
      ansible.builtin.command: >
        subscription-manager register
        --username={{ ansible_user }}
        --password={{ ansible_password }}
        --force

    - name: Verify the system is registered
      ansible.builtin.command: subscription-manager status
      register: subscription_status

    - name: Print subscription status
      ansible.builtin.debug:
        var: subscription_status.stdout
