---
- name: Expose LB Web Serive
  hosts: localhost
  tasks:

    - name: Create the service construct
        kubernetes.core.k8s:
          src: service.yaml
          namespace: arrowvirt
          state: present

 #  - name: Create the route construct
 #      kubernetes.core.k8s:
 #        src: route.yaml
 #        namespace: arrowvirt
 #        state: present
