---
- name: Create a Service in OpenShift 4
  hosts: localhost
  tasks:
    - name: Create a service in OpenShift using the k8s module
      k8s:
        state: present
        definition: "{{ lookup('file', 'service.yaml') }}"
        namespace: arrowvirt  # Specify your OpenShift namespace

    - name: Verify the service creation
      k8s_info:
        kind: Service
        namespace: arrowvirt
        name: web
      register: service_info

    - name: Display service information
      debug:
        msg: "{{ service_info.resources }}"

    - name: Create a route in OpenShift using the k8s module
      k8s:
        state: present
        definition: "{{ lookup('file', 'route.yaml') }}"
        namespace: arrowvirt  # Specify your OpenShift namespace   
