---
- name: Create a Service in OpenShift
  hosts: localhost
  tasks:
    - name: Create a service in OpenShift
      k8s:
        state: present
        definition: "{{ lookup('file', 'service.yaml') }}"
        namespace: arrowvirt
      when: lookup('file', 'service.yaml') is not failed

 #  - name: Create the route construct
 #      kubernetes.core.k8s:
 #        src: route.yaml
 #        namespace: arrowvirt
 #        state: present
